### ISSUE TITLE
Etymology lookup through etymonline

### ISSUE THREAD

**Issue by henry232323** [henry232323/Anglish-Bot#2]
We can make any other etymology source work, main problem is that most easily accessible ones reference through wiktionary. Best solution would be to get data from both Etymonline and wiktionary based sources

**Comment by schradert** [comment]
Just seeing this now. I'll put something together with the wikimedia api this weekend when I have free time and then link it here. if we want to scrape, we'll need a quality parser and a good idea of what exact information users care about in the etymology section.
